sonar.projectKey=billing-framework
sonar.projectName=billing-framework
sonar.sources=packages,services
sonar.tests=packages,services,tools
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
